/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import model.*;

public class UserFrame extends javax.swing.JFrame {
    DefaultListModel userList = new DefaultListModel<String>();
    DefaultListModel tweetList = new DefaultListModel<String>();
    AdminControl admin = AdminControl.getInstance();
    User user;
    /**
     * Creates new form UserFrame
     */
    public UserFrame(User user) {
        super();
        this.user = user;
        initComponents();
        userID.setText("");
        CreationTimeLabel.setText("Created : " + new Date(user.getCreatedTime()));
        List<Integer> followings = user.getFollowings();
        for (int id: followings) {
            if (id != user.getID()) {
                userList.addElement(admin.getComponentByID(id));
            }
        }
        
        for (Tweet t : user.getTweets()) {
            tweetList.addElement(t);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userDetailPanel = new javax.swing.JPanel();
        userID = new javax.swing.JTextField();
        followUser = new javax.swing.JButton();
        currentFollowingScrollPane = new javax.swing.JScrollPane();
        currentFollowingList = new javax.swing.JList<>();
        tweetScrollPane = new javax.swing.JScrollPane();
        tweetMessage = new javax.swing.JTextArea();
        postTweet = new javax.swing.JButton();
        newsFeedScrollPane = new javax.swing.JScrollPane();
        newsFeedList = new javax.swing.JList<>();
        CreationTimeLabel = new javax.swing.JLabel();
        lastUpdatedLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userID.setText("User ID");
        userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDActionPerformed(evt);
            }
        });

        followUser.setText("Follow User");
        followUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                followUserMouseClicked(evt);
            }
        });
        followUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                followUserActionPerformed(evt);
            }
        });

        currentFollowingList.setModel(userList);
        currentFollowingList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        currentFollowingScrollPane.setViewportView(currentFollowingList);

        tweetMessage.setColumns(20);
        tweetMessage.setRows(5);
        tweetScrollPane.setViewportView(tweetMessage);

        postTweet.setText("Post Tweet");
        postTweet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postTweetMouseClicked(evt);
            }
        });

        newsFeedList.setModel(tweetList);
        newsFeedList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        newsFeedScrollPane.setViewportView(newsFeedList);

        CreationTimeLabel.setText("Creation Time");

        lastUpdatedLabel.setText("Last Updated");

        javax.swing.GroupLayout userDetailPanelLayout = new javax.swing.GroupLayout(userDetailPanel);
        userDetailPanel.setLayout(userDetailPanelLayout);
        userDetailPanelLayout.setHorizontalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(currentFollowingScrollPane)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addComponent(tweetScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(postTweet))
            .addComponent(newsFeedScrollPane)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addComponent(userID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(followUser)
                .addContainerGap())
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreationTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastUpdatedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userDetailPanelLayout.setVerticalGroup(
            userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userDetailPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(CreationTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(followUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentFollowingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lastUpdatedLabel)
                .addGroup(userDetailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userDetailPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(postTweet)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userDetailPanelLayout.createSequentialGroup()
                        .addComponent(tweetScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(newsFeedScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userDetailPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userDetailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userIDActionPerformed

    private void followUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_followUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_followUserActionPerformed

    private void followUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_followUserMouseClicked
        System.out.println("followUserMouseClicked");
        Component c = admin.getComponentByName(userID.getText());
        if (c instanceof User) {
            User user = (User)c;
            this.user.follow(user.getID());
            userList.addElement(c);
        }
    }//GEN-LAST:event_followUserMouseClicked

    private void postTweetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postTweetMouseClicked
        System.out.println("postTweetMouseClicked");
        Tweet tweet = new Tweet(tweetMessage.getText(), user);
        user.publish(tweet);
        tweetList.addElement(tweet);
        lastUpdatedLabel.setText("Last Updated : " + (new Date(user.getLastUpdatedTime())));

    }//GEN-LAST:event_postTweetMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CreationTimeLabel;
    private javax.swing.JList<String> currentFollowingList;
    private javax.swing.JScrollPane currentFollowingScrollPane;
    private javax.swing.JButton followUser;
    private javax.swing.JLabel lastUpdatedLabel;
    private javax.swing.JList<String> newsFeedList;
    private javax.swing.JScrollPane newsFeedScrollPane;
    private javax.swing.JButton postTweet;
    private javax.swing.JTextArea tweetMessage;
    private javax.swing.JScrollPane tweetScrollPane;
    private javax.swing.JPanel userDetailPanel;
    private javax.swing.JTextField userID;
    // End of variables declaration//GEN-END:variables
}
